'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ChevronRight, Clock3, RotateCcw, Send, Trophy } from 'lucide-react';

type RoundQuestion = { round: string; kind: string; prompt: string; followUp: string; keywords: string[] };
const rounds: RoundQuestion[] = [
  { round: 'Round 1 · SQL screening', kind: 'Coding + reasoning', prompt: 'You have duplicate customer records. How would you identify the latest valid record per customer while handling tied timestamps?', followUp: 'What would you change if two records have the same timestamp and different values?', keywords: ['row_number', 'partition', 'order', 'tie'] },
  { round: 'Round 2 · Data Engineering', kind: 'Production scenario', prompt: 'Your Spark pipeline normally takes 25 minutes but suddenly takes four hours without a code change. What do you investigate first?', followUp: 'How would you prove whether the problem is data skew or insufficient cluster resources?', keywords: ['skew', 'shuffle', 'partition', 'input', 'executor', 'spill'] },
  { round: 'Round 3 · System design', kind: 'Architecture', prompt: 'Design a pipeline processing 100 million events per day with replay, data quality checks, lineage, and cost-aware storage.', followUp: 'How do you make the pipeline idempotent when a batch is retried?', keywords: ['partition', 'idempotent', 'quality', 'monitor', 'storage', 'retry'] },
  { round: 'Round 4 · Behavioral', kind: 'Communication', prompt: 'Tell me about a time you found a data quality issue. How did you communicate the impact and drive it to resolution?', followUp: 'What would you do if the stakeholder disagreed with your assessment?', keywords: ['impact', 'communicate', 'root', 'fix', 'measure'] },
];

export default function RoundSimulatorPage() {
  const [role, setRole] = useState('Data Engineer'); const [experience, setExperience] = useState('0–1 years'); const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(''); const [score, setScore] = useState(0); const [feedback, setFeedback] = useState(''); const [done, setDone] = useState(false);
  const question = rounds[index];
  const readiness = Math.round((score / rounds.length) * 100);
  const answerScore = useMemo(() => { const normalized = answer.toLowerCase(); return question?.keywords.filter(keyword => normalized.includes(keyword)).length || 0; }, [answer, question]);
  function submit() { const earned = answer.length >= 80 ? Math.min(1, answerScore / 3) : 0; setScore(value => value + earned); setFeedback(earned >= .66 ? 'Strong signal. Your reasoning included multiple evidence points.' : earned > 0 ? 'Partial signal. Add trade-offs, failure handling, and how you would verify the diagnosis.' : 'Needs more evidence. Structure your answer with approach, edge cases, and verification.'); }
  function next() { if (index === rounds.length - 1) setDone(true); else { setIndex(value => value + 1); setAnswer(''); setFeedback(''); } }
  function reset() { setIndex(0); setAnswer(''); setScore(0); setFeedback(''); setDone(false); }
  return <main className="interview-page"><div className="interview-wrap simulator-wrap"><Link href="/" className="back-link"><ArrowLeft size={15} /> Back to dashboard</Link><header className="interview-header"><div><span className="eyebrow">ROUND SIMULATOR</span><h1>Practice the pressure, safely.</h1><p>One question at a time, with a follow-up designed around the reasoning gap in your answer.</p></div><div className="simulator-score"><Trophy size={17} /><span>{Math.round((score / rounds.length) * 100)}%</span><small>practice readiness</small></div></header><div className="simulator-config"><label>Role<select value={role} onChange={event => setRole(event.target.value)}><option>Data Engineer</option><option>Data Analyst</option><option>Analytics Engineer</option></select></label><label>Experience<select value={experience} onChange={event => setExperience(event.target.value)}><option>0–1 years</option><option>1–3 years</option><option>3–5 years</option><option>5+ years</option></select></label><span><Clock3 size={15} /> {rounds.length} rounds · {role} · {experience}</span></div>{!done ? <section className="simulator-card"><div className="simulator-progress"><span>{question.round}</span><span>{index + 1} / {rounds.length}</span></div><div className="simulator-kind">{question.kind}</div><h2>Interviewer</h2><p className="simulator-prompt">{question.prompt}</p><textarea value={answer} onChange={event => setAnswer(event.target.value)} placeholder="Think aloud. Explain your approach, assumptions, edge cases, and how you would verify it." /><div className="simulator-actions">{feedback && <span className="sim-feedback">{feedback}</span>}<button className="primary-button" onClick={feedback ? next : submit} disabled={!answer.trim()}>{feedback ? index === rounds.length - 1 ? 'Finish report' : 'Continue' : 'Submit answer'} {feedback ? <ChevronRight size={14} /> : <Send size={14} />}</button></div>{feedback && <div className="follow-up"><span className="eyebrow">FOLLOW-UP</span><strong>{question.followUp}</strong></div>}</section> : <section className="simulator-card report-card"><span className="eyebrow">INTERVIEW REPORT</span><h2>{role} · {experience}</h2><div className="report-score">{readiness}%<small> practice readiness</small></div><p>Current simulated performance against this configured practice benchmark. This is not a prediction of an employer decision.</p><div className="report-grid"><div><span>Rounds</span><strong>{rounds.length}</strong></div><div><span>Questions</span><strong>{rounds.length * 2}</strong></div><div><span>Mode</span><strong>{role}</strong></div></div><button className="outline-button" onClick={reset}><RotateCcw size={14} /> Run another mock</button></section>}</div></main>;
}
