const defaultState={xp:1840,streak:8,completed:false,mastery:{'SQL':82,'Python':76,'Pandas':68,'Analytics':74,'Data Warehousing':52,'PySpark':61,'Databricks':67,'Cloud':41,'Airflow':35}};
const questions=[
 {topic:'Data Warehousing',difficulty:'Medium',prompt:'A customer changes their address. Your warehouse must preserve the old address for historical reports and show the new address for future orders. Which approach fits?',options:['Overwrite the existing row in place','Add a new dimension row and expire the previous row','Delete the customer and reload all facts','Store both addresses in a comma-separated column'],answer:1,explain:'SCD Type 2 adds a new versioned dimension row and closes the previous version with effective dates.'},
 {topic:'PySpark',difficulty:'Hard',prompt:'A 2 GB customer dimension is joined to a 4 TB events table. The dimension fits comfortably in executor memory. Which optimization is the strongest first move?',options:['Call repartition(1) before the join','Use a broadcast join for the dimension','Cache the events table after every transformation','Convert the join into a Python UDF'],answer:1,explain:'Broadcasting the small dimension avoids shuffling the 4 TB fact side across the cluster.'},
 {topic:'Databricks',difficulty:'Medium',prompt:'A pipeline may be retried after a partial failure. Which Delta Lake pattern best prevents duplicate records in the gold table?',options:['Append every retry and deduplicate in Power BI','Use an idempotent MERGE keyed by the business identifier','Disable retries on the job','Write directly to a CSV file'],answer:1,explain:'A deterministic MERGE makes reruns safe by updating existing business keys and inserting only new records.'}
];
let state=JSON.parse(localStorage.getItem('dataforge-state')||'null')||structuredClone(defaultState);let currentQuestion=0;let selected=null;let answered=false;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function renderMastery(){const entries=Object.entries(state.mastery).slice(0,5);$('#mastery-list').innerHTML=entries.map(([name,score])=>`<div class="mastery-row"><div class="mastery-name"><span>${name}</span><span class="mastery-score">${score}%</span></div><div class="progress-track"><span style="width:${score}%"></span></div></div>`).join('');$('#mastery-detail').innerHTML=Object.entries(state.mastery).map(([name,score])=>`<article class="detail-card"><span class="eyebrow">TOPIC SIGNAL</span><span class="detail-score">${score}%</span><h3>${name}</h3><div class="progress-track"><span style="width:${score}%"></span></div><dl><dt>Recent performance</dt><dd>${Math.max(score-5,20)}%</dd><dt>Retention estimate</dt><dd>${Math.min(score+7,98)}%</dd><dt>Next review</dt><dd>${score<60?'Tomorrow':'In 7 days'}</dd></dl></article>`).join('');}
function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
function go(view){$$('.view').forEach(el=>el.classList.remove('active-view'));$(`#${view}-view`).classList.add('active-view');$$('.nav-item').forEach(btn=>btn.classList.toggle('active',btn.dataset.view===view));const titles={dashboard:['Good morning, Arvind','MONDAY, SEPTEMBER 19, 2026'],test:["Today's challenge",'ADAPTIVE DAILY TEST'],mastery:['Topic mastery','YOUR SKILL MAP'],projects:['Project forge','BUILD TO REMEMBER'],analytics:['Your analytics','PERFORMANCE SIGNALS']};$('#view-title').textContent=titles[view][0];$('#view-eyebrow').textContent=titles[view][1];if(view==='test')renderQuestion();window.scrollTo({top:0,behavior:'smooth'});}
function renderQuestion(){const q=questions[currentQuestion];$('#question-count').textContent=`Question ${currentQuestion+1} of ${questions.length}`;$('#test-progress').style.width=`${((currentQuestion+1)/questions.length)*100}%`;$('#test-stage').innerHTML=`<article class="test-card"><div class="question-meta"><span>${q.topic}</span><span class="difficulty">${q.difficulty}</span></div><h2 class="question-title">${q.prompt}</h2><div>${q.options.map((option,i)=>`<button class="test-option" data-option="${i}"><span class="option-letter">0${i+1}</span><span>${option}</span></button>`).join('')}</div><div class="test-footer"><span class="hint">Think about the behavior you need on a retry.</span><button class="primary-button" id="submit-answer" disabled>Check answer <span>-></span></button></div></article>`;selected=null;answered=false;$$('.test-option').forEach(btn=>btn.addEventListener('click',()=>{if(answered)return;selected=Number(btn.dataset.option);$$('.test-option').forEach(item=>item.classList.remove('selected'));btn.classList.add('selected');$('#submit-answer').disabled=false}));$('#submit-answer').addEventListener('click',checkAnswer);}
function checkAnswer(){const q=questions[currentQuestion];answered=true;const correct=selected===q.answer;$$('.test-option')[q.answer].classList.add('selected');if(!correct)$$('.test-option')[selected].style.borderColor='var(--coral)';const topic=q.topic;state.mastery[topic]=Math.min(100,state.mastery[topic]+(correct?2:0));localStorage.setItem('dataforge-state',JSON.stringify(state));const footer=$('.test-footer');footer.innerHTML=`<span class="hint"><strong>${correct?'Correct.':'Not quite.'}</strong> ${q.explain}</span><button class="primary-button" id="next-question">${currentQuestion===questions.length-1?'Finish test':'Next question'} <span>-></span></button>`;$('#next-question').addEventListener('click',()=>{if(currentQuestion===questions.length-1){state.xp+=50;state.completed=true;localStorage.setItem('dataforge-state',JSON.stringify(state));renderMastery();showToast('Test complete. +50 XP and a sharper next plan.');go('dashboard')}else{currentQuestion++;renderQuestion()}})}
$$('[data-view]').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.view)));renderMastery();$('#streak-value').textContent=state.streak;
