'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Check, ChevronRight, Target } from 'lucide-react';

type Profile = { name: string; role: string; target: string; level: string; hours: string; topics: string };
const blankProfile: Profile = { name: 'Arvind', role: 'Early-career professional', target: 'Data Engineer + Data Analyst', level: 'Starting fresh', hours: '7:30–8:30 AM and 9:00–10:00 PM', topics: 'SQL, Python, Analytics' };

export default function ProfilePage() {
  const [profile, setProfile] = useState(blankProfile); const [saved, setSaved] = useState(false);
  useEffect(() => { const value = localStorage.getItem('dataforge-profile'); if (value) setProfile({ ...blankProfile, ...JSON.parse(value) }); }, []);
  function save(event: FormEvent) { event.preventDefault(); localStorage.setItem('dataforge-profile', JSON.stringify(profile)); setSaved(true); setTimeout(() => setSaved(false), 2400); }
  return <main className="profile-page"><div className="profile-wrap"><Link className="back-link" href="/"><ArrowLeft size={15} /> Back to dashboard</Link><header className="profile-header"><div className="large-avatar">AS</div><div><span className="eyebrow">LEARNER PROFILE</span><h1>{profile.name}</h1><p>Shape the system around the work you want to become capable of.</p></div></header><form className="profile-form" onSubmit={save}><section className="profile-section"><div><span className="eyebrow">IDENTITY</span><h2>About you</h2><p>These details tune your learning recommendations.</p></div><div className="field-grid"><label>Name<input value={profile.name} onChange={event => setProfile({ ...profile, name: event.target.value })} /></label><label>Current role<input value={profile.role} onChange={event => setProfile({ ...profile, role: event.target.value })} /></label><label>Target role<input value={profile.target} onChange={event => setProfile({ ...profile, target: event.target.value })} /></label><label>Current level<select value={profile.level} onChange={event => setProfile({ ...profile, level: event.target.value })}><option>Starting fresh</option><option>Early career</option><option>Intermediate</option><option>Advanced</option></select></label></div></section><section className="profile-section"><div><span className="eyebrow">LEARNING CONTRACT</span><h2>Your constraints</h2><p>Good plans fit real life, not an imaginary schedule.</p></div><div className="field-grid"><label>Available hours<input value={profile.hours} onChange={event => setProfile({ ...profile, hours: event.target.value })} /></label><label>Topics you already know<input value={profile.topics} onChange={event => setProfile({ ...profile, topics: event.target.value })} /></label></div></section><div className="profile-actions"><Link className="outline-button" href="/settings">Account settings <ChevronRight size={13} /></Link><button className="primary-button" type="submit">{saved ? <><Check size={14} /> Saved</> : <>Save profile <ChevronRight size={14} /></>}</button></div></form><aside className="profile-note"><Target size={18} /><div><strong>What changes when you save</strong><p>Daily priorities, baseline context, AI Coach prompts, and future review timing will use this profile.</p></div></aside></div></main>;
}
