'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { BarChart3, BookOpen, BrainCircuit, ChevronRight, Flame, LayoutDashboard, LogOut, Menu, Route, Settings, Sparkles, Target, Trophy, X } from 'lucide-react';
import { createClient } from '@/lib/supabase/browser';
import { masteryCurriculum } from '@/lib/mastery-data';

type Topic = { name: string; score: number };
type Progress = { xp: number; streak: number; testsCompleted: number; topics: Topic[] };

const initialTopics: Topic[] = masteryCurriculum.map(item => ({ name: item.name, score: 0 }));
const initialProgress: Progress = { xp: 0, streak: 0, testsCompleted: 0, topics: initialTopics };
const plan = [
  { tag: 'START HERE', tone: 'red', name: 'SQL foundations', area: 'SQL', time: '20 min', reason: 'Build your first signal' },
  { tag: 'START HERE', tone: 'amber', name: 'Python foundations', area: 'Python', time: '20 min', reason: 'Begin your baseline' },
  { tag: 'START HERE', tone: 'teal', name: 'Warehouse concepts', area: 'Data Warehousing', time: '15 min', reason: 'Create your first edge' },
];
const answers = ['Overwrite the existing row in place', 'Add a new dimension row and expire the previous row', 'Delete the customer and reload all facts', 'Store both addresses in a comma-separated column'];
type SkillQuestion = { topic: string; difficulty: string; prompt: string; options: string[]; answer: number };
const skillQuestions: SkillQuestion[] = [
  { topic: 'SQL', difficulty: 'Easy', prompt: 'Which SQL clause filters grouped results after aggregation?', options: ['WHERE', 'HAVING', 'ORDER BY', 'LIMIT'], answer: 1 },
  { topic: 'Python', difficulty: 'Easy', prompt: 'Which Python structure preserves insertion order and maps unique keys to values?', options: ['set', 'tuple', 'dict', 'iterator'], answer: 2 },
  { topic: 'Pandas', difficulty: 'Medium', prompt: 'Which Pandas operation combines rows from two DataFrames using matching keys?', options: ['merge', 'melt', 'pivot', 'explode'], answer: 0 },
  { topic: 'Analytics', difficulty: 'Medium', prompt: 'A metric moves from 100 to 125. What is the percentage increase?', options: ['20%', '25%', '30%', '125%'], answer: 1 },
  { topic: 'Data Warehousing', difficulty: 'Medium', prompt: 'A customer changes their address. How do you preserve the old address for historical reports?', options: ['Overwrite the row', 'Add a new dimension version and expire the old one', 'Delete all customer facts', 'Store both values in one string'], answer: 1 },
  { topic: 'PySpark', difficulty: 'Hard', prompt: 'A small dimension joins a huge events table. Which optimization usually avoids shuffling the large side?', options: ['repartition(1)', 'broadcast join', 'Python UDF', 'collect to the driver'], answer: 1 },
  { topic: 'Databricks', difficulty: 'Medium', prompt: 'Which Delta Lake operation makes an incremental load idempotent by updating existing keys and inserting new ones?', options: ['VACUUM', 'OPTIMIZE', 'MERGE', 'DESCRIBE HISTORY'], answer: 2 },
  { topic: 'Cloud', difficulty: 'Easy', prompt: 'Which AWS service is designed for durable object storage for raw data files?', options: ['S3', 'EC2', 'IAM', 'CloudWatch'], answer: 0 },
  { topic: 'Airflow', difficulty: 'Medium', prompt: 'What is the Airflow component responsible for deciding when scheduled task instances should run?', options: ['Worker', 'Scheduler', 'XCom', 'Operator'], answer: 1 },
];
function loadProgress(): Progress {
  if (typeof window === 'undefined') return initialProgress;
  try {
    const stored = JSON.parse(localStorage.getItem('dataforge-progress') || 'null') as Partial<Progress> | null;
    if (!stored || !Array.isArray(stored.topics)) return initialProgress;
    return { ...initialProgress, ...stored, topics: initialTopics.map(topic => stored.topics?.find(item => item.name === topic.name) || topic) };
  } catch { return initialProgress; }
}

export default function Dashboard({ email }: { email: string }) {
  const [view, setView] = useState('Dashboard');
  const [open, setOpen] = useState(false);
  const [progress, setProgress] = useState<Progress>(initialProgress);
  const [testComplete, setTestComplete] = useState(false);

  useEffect(() => setProgress(loadProgress()), []);
  function saveProgress(next: Progress) { setProgress(next); localStorage.setItem('dataforge-progress', JSON.stringify(next)); }
  async function signOut() {
    if (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) await createClient().auth.signOut();
    window.location.assign('/auth/login');
  }
  const nav = [['Dashboard', LayoutDashboard], ['Daily test', BookOpen], ['Topic mastery', Target], ['Projects', BrainCircuit], ['Analytics', BarChart3]] as const;
  const startTest = () => { setTestComplete(false); setView('Daily test'); };

  return <div className="product-shell"><aside className={`product-sidebar ${open ? 'open' : ''}`}><div className="product-brand"><span className="brand-mark">DF</span><span>DataForge</span></div><div className="workspace-label">LEARNING OS <span className="status-dot" /></div><nav>{nav.map(([label, Icon]) => <button key={label} className={view === label ? 'active' : ''} onClick={() => { setView(label); setOpen(false); }}><Icon size={16} />{label}</button>)}<button onClick={() => setView('Daily test')}><BookOpen size={16} />Practice</button><button onClick={() => setView('Topic mastery')}><Route size={16} />Learning Path</button><button onClick={() => window.location.assign('/interview-intelligence')}><Sparkles size={16} />Interview Intelligence</button><button onClick={() => window.location.assign('/round-simulator')}><Trophy size={16} />Round Simulator</button><button onClick={() => window.location.assign('/leaderboard')}><Trophy size={16} />Leaderboard</button><button onClick={() => window.location.assign('/settings')}><Settings size={16} />Settings</button></nav><div className="sidebar-bottom"><div className="coach-card"><span className="eyebrow">AI COACH</span><strong>Your first best move</strong><p>Complete the baseline test so DataForge can learn where to focus.</p><button onClick={startTest}>Start baseline <ChevronRight size={13} /></button></div><button className="profile-button" onClick={() => window.location.assign('/profile')}><span className="avatar">AS</span><span><strong>{email.split('@')[0]}</strong><small>{progress.xp} XP · {progress.testsCompleted} tests</small></span></button><button className="signout-button" onClick={signOut}><LogOut size={14} /> Sign out</button></div></aside><main className="product-main"><header className="product-topbar"><button className="mobile-menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><div><span className="eyebrow">MONDAY, SEPTEMBER 19, 2026</span><h1>{view === 'Dashboard' ? 'Good morning, Arvind' : view}</h1></div><div className="top-avatar">AS</div></header>{view === 'Dashboard' && <DashboardHome progress={progress} onStart={startTest} />}{view === 'Daily test' && <TestView complete={testComplete} onComplete={() => { if (testComplete) return; const next = { ...progress, xp: progress.xp + 50, streak: progress.streak + 1, testsCompleted: progress.testsCompleted + 1, topics: progress.topics.map(topic => topic.name === 'Data Warehousing' ? { ...topic, score: 8 } : topic) }; saveProgress(next); setTestComplete(true); }} />}{view === 'Topic mastery' && <MasteryView topics={progress.topics} />}{view === 'Projects' && <ProjectsView />}{view === 'Analytics' && <AnalyticsView progress={progress} />}</main></div>;
}

function DashboardHome({ progress, onStart }: { progress: Progress; onStart: () => void }) { const readiness = Math.round(progress.topics.reduce((sum, topic) => sum + topic.score, 0) / progress.topics.length); return <><div className="hero-grid"><div className="readiness-panel"><div className="panel-topline"><span className="eyebrow">TODAY'S READINESS</span><span className="readiness-change">Baseline pending</span></div><div className="readiness-number">{readiness}<span>%</span></div><p>Your learning profile starts at zero. Complete the baseline test and DataForge will build an evidence-based plan around you.</p><div className="progress-track large"><span style={{ width: `${readiness}%` }} /></div><div className="progress-meta"><span>Measured readiness</span><span>{readiness} / 100</span></div></div><div className="streak-panel"><div className="panel-topline"><span className="eyebrow">CURRENT STREAK</span><Flame size={18} /></div><div className="streak-number">{progress.streak} <small>days</small></div><div className="week-dots">{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, index) => <span className={index < progress.streak % 7 ? 'done' : ''} key={`${day}-${index}`}>{day}</span>)}</div><p>{progress.streak ? 'Keep your rhythm alive.' : 'Your first day starts with one test.'}</p></div></div><SectionHeading label="YOUR FIRST BEST MOVES" title="Today's plan" action="Start baseline" onAction={onStart} /><div className="plan-grid">{plan.map((item, index) => <article className={`plan-card ${item.tone}`} key={item.name}><span className="card-index">0{index + 1}</span><div><span className={`tag ${item.tone}`}>{item.tag}</span><h3>{item.name}</h3><p>{item.area} <span>·</span> {item.time}</p><div className="plan-footer"><span>{item.reason}</span><button onClick={onStart}>Practice <ChevronRight size={13} /></button></div></div></article>)}</div><div className="dashboard-lower"><section><SectionHeading label="EVIDENCE BUILDS MASTERY" title="Topic mastery" action="See all topics" onAction={() => {}} /><div className="mastery-list">{progress.topics.slice(0, 5).map(topic => <div className="mastery-row" key={topic.name}><div className="mastery-name"><span>{topic.name}</span><strong>{topic.score}%</strong></div><div className="progress-track"><span style={{ width: `${topic.score}%` }} /></div></div>)}</div></section><aside className="test-cta"><span className="eyebrow">BASELINE TEST</span><h2>Start at zero.<br /><em>Build real signal.</em></h2><p>15 questions will establish your first evidence-based learning profile.</p><button className="primary-button" onClick={onStart}>Start baseline test <ChevronRight size={14} /></button><div className="cta-meta"><span>~20 min</span><span>+50 XP completion</span></div></aside></div></> }
function SectionHeading({ label, title, action, onAction }: { label: string; title: string; action: string; onAction: () => void }) { return <div className="section-heading"><div><span className="eyebrow">{label}</span><h2>{title}</h2></div><button className="outline-button" onClick={onAction}>{action} <ChevronRight size={13} /></button></div> }
function TestView({ complete, onComplete }: { complete: boolean; onComplete: () => void }) {
  const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [selected, setSelected] = useState<number | null>(null); const [results, setResults] = useState<Record<string, number>>({}); const [finished, setFinished] = useState(complete);
  const question = skillQuestions[index];
  function choose(option: number) { if (selected !== null || finished) return; setSelected(option); }
  function next() {
    if (selected === null) return;
    const nextScore = score + (selected === question.answer ? 1 : 0); const nextResults = { ...results, [question.topic]: selected === question.answer ? 8 : 0 };
    if (index === skillQuestions.length - 1) {
      const topicScores = skillQuestions.map(item => ({ name: item.topic, score: nextResults[item.topic] || 0 }));
      setScore(nextScore); setResults(nextResults); setFinished(true); onComplete();
      const current = JSON.parse(localStorage.getItem('dataforge-progress') || 'null') || initialProgress;
      localStorage.setItem('dataforge-progress', JSON.stringify({ ...current, topics: initialTopics.map(topic => { const previous = current.topics?.find((item: Topic) => item.name === topic.name)?.score || 0; const measured = topicScores.find(item => item.name === topic.name)?.score || 0; return { ...topic, score: Math.max(previous, measured) }; }) }));
    } else { setScore(nextScore); setResults(nextResults); setIndex(index + 1); setSelected(null); }
  }
  if (finished) return <section className="simple-view"><span className="eyebrow">SKILL SWEEP COMPLETE</span><h2>Your first evaluation</h2><p>Evidence collected across {skillQuestions.length} core Data Engineering and Analytics skills.</p><div className="test-card evaluation-summary"><div className="evaluation-score">{score}<small> / {skillQuestions.length}</small></div><h3>{score >= 7 ? 'Strong first signal.' : score >= 4 ? 'A useful starting signal.' : 'A clear place to begin.'}</h3><p>Return to Topic Mastery to see the skill-by-skill breakdown. Your next test will use these results.</p><button className="primary-button" onClick={() => window.location.assign('/')}>Return to dashboard <ChevronRight size={14} /></button></div></section>;
  return <section className="simple-view"><span className="eyebrow">SKILL SWEEP · {index + 1} OF {skillQuestions.length}</span><h2>{question.topic} check</h2><p>One question per skill. Accuracy changes your learning plan.</p><div className="test-card"><div className="question-meta"><span className={`tag ${question.difficulty === 'Hard' ? 'red' : 'teal'}`}>{question.topic}</span><span className="difficulty-chip">{question.difficulty}</span></div><h3>{question.prompt}</h3>{question.options.map((option, optionIndex) => <button className={`test-option ${selected === optionIndex ? 'selected' : ''}`} key={option} onClick={() => choose(optionIndex)}><span>0{optionIndex + 1}</span>{option}</button>)}<div className="test-footer"><span className="test-hint">Select an answer, then continue.</span><button className="primary-button" disabled={selected === null} onClick={next}>{index === skillQuestions.length - 1 ? 'Finish evaluation' : 'Next skill'} <ChevronRight size={14} /></button></div></div></section>;
}
function MasteryView({ topics }: { topics: Topic[] }) {
  const [expanded, setExpanded] = useState<string | null>(null);
  return <section className="simple-view"><span className="eyebrow">YOUR SKILL MAP</span><h2>Topic mastery</h2><p>Every score starts at zero and changes only after a measured attempt. Open a skill to see its subtopics and ten explained practice questions.</p><div className="mastery-detail-grid">{masteryCurriculum.map(item => { const score = topics.find(topic => topic.name === item.name)?.score || 0; const isOpen = expanded === item.name; return <article className={`detail-card mastery-topic ${isOpen ? 'expanded' : ''}`} key={item.name}><button className="mastery-topic-button" onClick={() => setExpanded(isOpen ? null : item.name)}><span><span className="eyebrow">SKILL</span><h3>{item.name}</h3></span><strong>{score}%</strong></button><div className="progress-track"><span style={{ width: `${score}%` }} /></div><div className="mastery-topic-meta"><span>{item.subtopics.length} subtopics · {item.questions.length} questions</span><span>{score ? 'Measured' : 'After baseline'}</span></div>{isOpen && <div className="mastery-topic-detail"><div className="mastery-practice-row"><span className="eyebrow">PRACTICE THIS SKILL</span><Link className="small-practice-button" href={`/practice/${encodeURIComponent(item.name.toLowerCase().replace(/\s+/g, '-'))}`}>Start {item.name} practice <ChevronRight size={13} /></Link></div><span className="eyebrow">SUBTOPICS</span><div className="subtopic-list">{item.subtopics.map(subtopic => <span key={subtopic}>{subtopic}</span>)}</div><span className="eyebrow">PRACTICE QUESTIONS · EXPLANATIONS · EXAMPLES</span><div className="mastery-questions">{item.questions.map((question, index) => <div key={question.prompt}><span>{String(index + 1).padStart(2, '0')}</span><div><p>{question.prompt}</p><small>Explanation: {question.explanation}</small><small>Example: {question.example}</small></div><em>{score ? 'Review' : 'Baseline pending'}</em></div>)}</div></div>}</article>; })}</div></section>
}
function ProjectsView() { const projects = [{ name: 'E-commerce data platform', topic: 'ETL and ELT', stack: 'Python · SQL · PySpark · Delta Lake · Power BI', focus: 'ETL, star schema, bronze/silver/gold', status: 'Start here', progress: 0 }, { name: 'Customer 360 analytics', topic: 'Data Modeling', stack: 'Python · SQL · Data Modeling · Analytics', focus: 'Identity resolution, SCD2, retention, CLV', status: 'Next track', progress: 0 }, { name: 'Sales analytics platform', topic: 'Power BI', stack: 'SQL · Power BI · Statistics', focus: 'Fact sales, dimensions, KPIs, DAX', status: 'Next track', progress: 0 }, { name: 'Reliable streaming pipeline', topic: 'PySpark', stack: 'PySpark · Databricks · Cloud · Airflow', focus: 'Streaming, quality, retries, monitoring', status: 'Advanced track', progress: 0 }]; const [selected, setSelected] = useState(0); const project = projects[selected]; return <section className="simple-view"><span className="eyebrow">BUILD TO REMEMBER</span><h2>Project forge</h2><p>Practice concepts in project-shaped work. Each track maps directly to your skill curriculum.</p><div className="project-layout"><div className="project-menu">{projects.map((item, index) => <button className={selected === index ? 'active' : ''} onClick={() => setSelected(index)} key={item.name}><span>0{index + 1}</span><strong>{item.name}</strong><small>{item.status} · {item.progress}%</small></button>)}</div><div className="project-feature"><span className="eyebrow">{project.status.toUpperCase()} · {project.progress}%</span><h2>{project.name}</h2><p>{project.focus}</p><div className="project-stack">{project.stack.split(' · ').map(tool => <span key={tool}>{tool}</span>)}</div><div className="pipeline">RAW <b>-&gt;</b> BRONZE <b>-&gt;</b> SILVER <b>-&gt;</b> GOLD</div><div className="progress-track"><span style={{ width: `${project.progress}%` }} /></div><button className="primary-button" onClick={() => window.location.assign(`/practice/${encodeURIComponent(project.topic.toLowerCase().replace(/\s+/g, '-'))}`)}>Open project practice <ChevronRight size={14} /></button></div></div></section> }
function AnalyticsView({ progress }: { progress: Progress }) { return <section className="simple-view"><span className="eyebrow">PERFORMANCE SIGNALS</span><h2>Your analytics</h2><p>Analytics will become meaningful after your first completed test.</p><div className="analytics-grid"><div className="chart-card"><span>Tests completed</span><strong>{progress.testsCompleted}</strong><div className="fake-chart" /></div><div className="stats-card"><span className="eyebrow">ALL TIME</span>{[['Questions answered', progress.testsCompleted ? '1' : '0'], ['Study time', progress.testsCompleted ? '20 min' : '0 min'], ['XP earned', `+${progress.xp}`], ['Current streak', `${progress.streak} days`]].map(([label, value]) => <div className="stat-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section> }
