'use client';

import { useEffect, useState } from 'react';
import { BarChart3, BookOpen, BrainCircuit, ChevronRight, Flame, LayoutDashboard, LogOut, Menu, Target, X } from 'lucide-react';
import { createClient } from '@/lib/supabase/browser';

type Topic = { name: string; score: number };
type Progress = { xp: number; streak: number; testsCompleted: number; topics: Topic[] };

const initialTopics: Topic[] = ['SQL', 'Python', 'Pandas', 'Analytics', 'Data Warehousing', 'PySpark', 'Databricks', 'Cloud', 'Airflow'].map(name => ({ name, score: 0 }));
const initialProgress: Progress = { xp: 0, streak: 0, testsCompleted: 0, topics: initialTopics };
const plan = [
  { tag: 'START HERE', tone: 'red', name: 'SQL foundations', area: 'SQL', time: '20 min', reason: 'Build your first signal' },
  { tag: 'START HERE', tone: 'amber', name: 'Python foundations', area: 'Python', time: '20 min', reason: 'Begin your baseline' },
  { tag: 'START HERE', tone: 'teal', name: 'Warehouse concepts', area: 'Data Warehousing', time: '15 min', reason: 'Create your first edge' },
];
const answers = ['Overwrite the existing row in place', 'Add a new dimension row and expire the previous row', 'Delete the customer and reload all facts', 'Store both addresses in a comma-separated column'];

function loadProgress(): Progress {
  if (typeof window === 'undefined') return initialProgress;
  try {
    const stored = JSON.parse(localStorage.getItem('dataforge-progress') || 'null') as Partial<Progress> | null;
    if (!stored || !Array.isArray(stored.topics)) return initialProgress;
    return { ...initialProgress, ...stored, topics: initialTopics.map(topic => stored.topics?.find(item => item.name === topic.name) || topic) };
  } catch { return initialProgress; }
}

export default function Dashboard({ email }: { email: string }) {
  const [view, setView] = useState('Dashboard');
  const [open, setOpen] = useState(false);
  const [progress, setProgress] = useState<Progress>(initialProgress);
  const [testComplete, setTestComplete] = useState(false);

  useEffect(() => setProgress(loadProgress()), []);
  function saveProgress(next: Progress) { setProgress(next); localStorage.setItem('dataforge-progress', JSON.stringify(next)); }
  async function signOut() {
    if (process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) await createClient().auth.signOut();
    window.location.assign('/auth/login');
  }
  const nav = [['Dashboard', LayoutDashboard], ['Daily test', BookOpen], ['Topic mastery', Target], ['Projects', BrainCircuit], ['Analytics', BarChart3]] as const;
  const startTest = () => { setTestComplete(false); setView('Daily test'); };

  return <div className="product-shell"><aside className={`product-sidebar ${open ? 'open' : ''}`}><div className="product-brand"><span className="brand-mark">DF</span><span>DataForge</span></div><div className="workspace-label">LEARNING OS <span className="status-dot" /></div><nav>{nav.map(([label, Icon]) => <button key={label} className={view === label ? 'active' : ''} onClick={() => { setView(label); setOpen(false); }}><Icon size={16} />{label}</button>)}</nav><div className="sidebar-bottom"><div className="coach-card"><span className="eyebrow">AI COACH</span><strong>Your first best move</strong><p>Complete the baseline test so DataForge can learn where to focus.</p><button onClick={startTest}>Start baseline <ChevronRight size={13} /></button></div><button className="profile-button" onClick={() => window.location.assign('/profile')}><span className="avatar">AS</span><span><strong>{email.split('@')[0]}</strong><small>{progress.xp} XP · {progress.testsCompleted} tests</small></span></button><button className="signout-button" onClick={signOut}><LogOut size={14} /> Sign out</button></div></aside><main className="product-main"><header className="product-topbar"><button className="mobile-menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><div><span className="eyebrow">MONDAY, SEPTEMBER 19, 2026</span><h1>{view === 'Dashboard' ? 'Good morning, Arvind' : view}</h1></div><div className="top-avatar">AS</div></header>{view === 'Dashboard' && <DashboardHome progress={progress} onStart={startTest} />}{view === 'Daily test' && <TestView complete={testComplete} onComplete={() => { if (testComplete) return; const next = { ...progress, xp: progress.xp + 50, streak: progress.streak + 1, testsCompleted: progress.testsCompleted + 1, topics: progress.topics.map(topic => topic.name === 'Data Warehousing' ? { ...topic, score: 8 } : topic) }; saveProgress(next); setTestComplete(true); }} />}{view === 'Topic mastery' && <MasteryView topics={progress.topics} />}{view === 'Projects' && <ProjectsView />}{view === 'Analytics' && <AnalyticsView progress={progress} />}</main></div>;
}

function DashboardHome({ progress, onStart }: { progress: Progress; onStart: () => void }) { const readiness = Math.round(progress.topics.reduce((sum, topic) => sum + topic.score, 0) / progress.topics.length); return <><div className="hero-grid"><div className="readiness-panel"><div className="panel-topline"><span className="eyebrow">TODAY'S READINESS</span><span className="readiness-change">Baseline pending</span></div><div className="readiness-number">{readiness}<span>%</span></div><p>Your learning profile starts at zero. Complete the baseline test and DataForge will build an evidence-based plan around you.</p><div className="progress-track large"><span style={{ width: `${readiness}%` }} /></div><div className="progress-meta"><span>Measured readiness</span><span>{readiness} / 100</span></div></div><div className="streak-panel"><div className="panel-topline"><span className="eyebrow">CURRENT STREAK</span><Flame size={18} /></div><div className="streak-number">{progress.streak} <small>days</small></div><div className="week-dots">{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, index) => <span className={index < progress.streak % 7 ? 'done' : ''} key={`${day}-${index}`}>{day}</span>)}</div><p>{progress.streak ? 'Keep your rhythm alive.' : 'Your first day starts with one test.'}</p></div></div><SectionHeading label="YOUR FIRST BEST MOVES" title="Today's plan" action="Start baseline" onAction={onStart} /><div className="plan-grid">{plan.map((item, index) => <article className={`plan-card ${item.tone}`} key={item.name}><span className="card-index">0{index + 1}</span><div><span className={`tag ${item.tone}`}>{item.tag}</span><h3>{item.name}</h3><p>{item.area} <span>·</span> {item.time}</p><div className="plan-footer"><span>{item.reason}</span><button onClick={onStart}>Practice <ChevronRight size={13} /></button></div></div></article>)}</div><div className="dashboard-lower"><section><SectionHeading label="EVIDENCE BUILDS MASTERY" title="Topic mastery" action="See all topics" onAction={() => {}} /><div className="mastery-list">{progress.topics.slice(0, 5).map(topic => <div className="mastery-row" key={topic.name}><div className="mastery-name"><span>{topic.name}</span><strong>{topic.score}%</strong></div><div className="progress-track"><span style={{ width: `${topic.score}%` }} /></div></div>)}</div></section><aside className="test-cta"><span className="eyebrow">BASELINE TEST</span><h2>Start at zero.<br /><em>Build real signal.</em></h2><p>15 questions will establish your first evidence-based learning profile.</p><button className="primary-button" onClick={onStart}>Start baseline test <ChevronRight size={14} /></button><div className="cta-meta"><span>~20 min</span><span>+50 XP completion</span></div></aside></div></> }
function SectionHeading({ label, title, action, onAction }: { label: string; title: string; action: string; onAction: () => void }) { return <div className="section-heading"><div><span className="eyebrow">{label}</span><h2>{title}</h2></div><button className="outline-button" onClick={onAction}>{action} <ChevronRight size={13} /></button></div> }
function TestView({ complete, onComplete }: { complete: boolean; onComplete: () => void }) { return <section className="simple-view"><span className="eyebrow">BASELINE DAILY TEST</span><h2>Your first signal</h2><p>No assumptions. Answer one realistic data engineering question to begin.</p><div className="test-card"><span className="tag red">DATA WAREHOUSING · MEDIUM</span><h3>A customer changes their address. Your warehouse must preserve the old address for historical reports and show the new address for future orders. Which approach fits?</h3>{answers.map((answer, index) => <button className={complete && index === 1 ? 'test-option selected' : 'test-option'} key={answer} onClick={onComplete}><span>0{index + 1}</span>{answer}</button>)}{complete && <p className="success-note">Baseline saved. +50 XP, 1 day streak, and Data Warehousing is now your first measured signal.</p>}{!complete && <p className="test-hint">Choose an answer to complete your baseline. Your first result will be saved locally.</p>}</div></section> }
function MasteryView({ topics }: { topics: Topic[] }) { return <section className="simple-view"><span className="eyebrow">YOUR SKILL MAP</span><h2>Topic mastery</h2><p>Every score starts at zero and changes only after a measured attempt.</p><div className="mastery-detail-grid">{topics.map(topic => <article className="detail-card" key={topic.name}><span className="eyebrow">TOPIC SIGNAL</span><strong>{topic.score}%</strong><h3>{topic.name}</h3><div className="progress-track"><span style={{ width: `${topic.score}%` }} /></div><dl><dt>Measured accuracy</dt><dd>{topic.score}%</dd><dt>Next review</dt><dd>{topic.score ? 'In 7 days' : 'After baseline'}</dd></dl></article>)}</div></section> }
function ProjectsView() { return <section className="simple-view"><span className="eyebrow">BUILD TO REMEMBER</span><h2>Project forge</h2><p>Projects unlock after you establish your baseline.</p><div className="project-feature"><span className="eyebrow">LOCKED · COMPLETE BASELINE FIRST</span><h2>E-commerce data platform</h2><p>Build a production-shaped pipeline from raw commerce events to a Power BI-ready gold layer.</p><div className="pipeline">CSV / API <b>-&gt;</b> BRONZE <b>-&gt;</b> SILVER <b>-&gt;</b> GOLD</div><div className="progress-track"><span style={{ width: '0%' }} /></div></div></section> }
function AnalyticsView({ progress }: { progress: Progress }) { return <section className="simple-view"><span className="eyebrow">PERFORMANCE SIGNALS</span><h2>Your analytics</h2><p>Analytics will become meaningful after your first completed test.</p><div className="analytics-grid"><div className="chart-card"><span>Tests completed</span><strong>{progress.testsCompleted}</strong><div className="fake-chart" /></div><div className="stats-card"><span className="eyebrow">ALL TIME</span>{[['Questions answered', progress.testsCompleted ? '1' : '0'], ['Study time', progress.testsCompleted ? '20 min' : '0 min'], ['XP earned', `+${progress.xp}`], ['Current streak', `${progress.streak} days`]].map(([label, value]) => <div className="stat-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section> }
