'use client';

import { useState } from 'react';
import { BarChart3, BookOpen, BrainCircuit, ChevronRight, Flame, LayoutDashboard, LogOut, Menu, Target, X } from 'lucide-react';
import { createClient } from '@/lib/supabase/browser';

const mastery = [['SQL',82],['Python',76],['Pandas',68],['Analytics',74],['Data Warehousing',52],['PySpark',61],['Databricks',67],['Cloud',41],['Airflow',35]] as const;
const plan = [{tag:'HIGH PRIORITY', tone:'red', name:'SCD Type 2', area:'Data Warehousing', time:'20 min', reason:'Repeated misses detected'}, {tag:'REINFORCE', tone:'amber', name:'PySpark joins', area:'PySpark', time:'20 min', reason:'Last seen 6 days ago'}, {tag:'BUILD ON', tone:'teal', name:'Delta Lake', area:'Databricks', time:'15 min', reason:'Ready for a harder level'}];

export default function Dashboard({ email }: { email: string }) {
  const [view, setView] = useState('Dashboard'); const [open, setOpen] = useState(false); const [testStarted, setTestStarted] = useState(false);
  const nav = [['Dashboard',LayoutDashboard],['Daily test',BookOpen],['Topic mastery',Target],['Projects',BrainCircuit],['Analytics',BarChart3]] as const;
  async function signOut() { await createClient().auth.signOut(); window.location.assign('/auth/login'); }
  return <div className="product-shell"><aside className={`product-sidebar ${open ? 'open' : ''}`}><div className="product-brand"><span className="brand-mark">DF</span><span>DataForge</span></div><div className="workspace-label">LEARNING OS <span className="status-dot" /></div><nav>{nav.map(([label, Icon]) => <button key={label} className={view === label ? 'active' : ''} onClick={() => { setView(label); setOpen(false); }}><Icon size={16} />{label}</button>)}</nav><div className="sidebar-bottom"><div className="coach-card"><span className="eyebrow">AI COACH</span><strong>Your next best move</strong><p>Reinforce SCD Type 2 before adding another warehouse pattern.</p><button onClick={() => setView('Daily test')}>Open practice <ChevronRight size={13} /></button></div><button className="profile-button"><span className="avatar">AS</span><span><strong>{email.split('@')[0]}</strong><small>Early career</small></span></button><button className="signout-button" onClick={signOut}><LogOut size={14} /> Sign out</button></div></aside><main className="product-main"><header className="product-topbar"><button className="mobile-menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><div><span className="eyebrow">MONDAY, SEPTEMBER 19, 2026</span><h1>{view === 'Dashboard' ? 'Good morning, Arvind' : view}</h1></div><div className="top-avatar">AS</div></header>{view === 'Dashboard' && <DashboardHome onStart={() => { setTestStarted(true); setView('Daily test'); }} />}{view === 'Daily test' && <TestView started={testStarted} onStart={() => setTestStarted(true)} />}{view === 'Topic mastery' && <MasteryView />}{view === 'Projects' && <ProjectsView />}{view === 'Analytics' && <AnalyticsView />}</main></div>;
}

function DashboardHome({ onStart }: { onStart: () => void }) { return <><div className="hero-grid"><div className="readiness-panel"><div className="panel-topline"><span className="eyebrow">TODAY'S READINESS</span><span className="readiness-change">+4.8% this week</span></div><div className="readiness-number">72<span>%</span></div><p>Your foundations are strong. The next lift comes from turning warehouse concepts into fluent decisions.</p><div className="progress-track large"><span style={{width:'72%'}} /></div><div className="progress-meta"><span>Current readiness</span><span>72 / 100</span></div></div><div className="streak-panel"><div className="panel-topline"><span className="eyebrow">CURRENT STREAK</span><Flame size={18} /></div><div className="streak-number">8 <small>days</small></div><div className="week-dots">{['M','T','W','T','F','S','S'].map((day, index) => <span className={index < 5 ? 'done' : index === 5 ? 'today' : ''} key={`${day}-${index}`}>{day}</span>)}</div><p>Keep your rhythm alive. A 15-minute test is waiting.</p></div></div><SectionHeading label="YOUR NEXT BEST MOVES" title="Today's plan" action="View full plan" onAction={onStart} /><div className="plan-grid">{plan.map((item,index) => <article className={`plan-card ${item.tone}`} key={item.name}><span className="card-index">0{index+1}</span><div><span className={`tag ${item.tone}`}>{item.tag}</span><h3>{item.name}</h3><p>{item.area} <span>·</span> {item.time}</p><div className="plan-footer"><span>{item.reason}</span><button onClick={onStart}>Practice <ChevronRight size={13} /></button></div></div></article>)}</div><div className="dashboard-lower"><section><SectionHeading label="SIGNAL, NOT JUST A SCORE" title="Topic mastery" action="See all topics" onAction={() => {}} /><div className="mastery-list">{mastery.slice(0,5).map(([name,score]) => <div className="mastery-row" key={name}><div className="mastery-name"><span>{name}</span><strong>{score}%</strong></div><div className="progress-track"><span style={{width:`${score}%`}} /></div></div>)}</div></section><aside className="test-cta"><span className="eyebrow">DAILY TEST</span><h2>15 questions.<br /><em>One clear next step.</em></h2><p>Adaptive mix based on your recent performance and retention.</p><button className="primary-button" onClick={onStart}>Start today's test <ChevronRight size={14} /></button><div className="cta-meta"><span>~20 min</span><span>+50 XP completion</span></div></aside></div></> }
function SectionHeading({label,title,action,onAction}:{label:string;title:string;action:string;onAction:()=>void}) { return <div className="section-heading"><div><span className="eyebrow">{label}</span><h2>{title}</h2></div><button className="outline-button" onClick={onAction}>{action} <ChevronRight size={13} /></button></div> }
function TestView({ started, onStart }: { started:boolean; onStart:()=>void }) { return <section className="simple-view"><span className="eyebrow">ADAPTIVE DAILY TEST</span><h2>Today's challenge</h2><p>A focused set built around your weak signals.</p><div className="test-card"><span className="tag red">DATA WAREHOUSING · MEDIUM</span><h3>A customer changes their address. Your warehouse must preserve the old address for historical reports and show the new address for future orders. Which approach fits?</h3>{['Overwrite the existing row in place','Add a new dimension row and expire the previous row','Delete the customer and reload all facts','Store both addresses in a comma-separated column'].map((answer,index)=><button className={started && index === 1 ? 'test-option selected' : 'test-option'} key={answer} onClick={onStart}><span>0{index+1}</span>{answer}</button>)}{started && <p className="success-note">Correct. SCD Type 2 adds a new versioned dimension row and closes the previous version with effective dates.</p>}</div></section> }
function MasteryView(){return <section className="simple-view"><span className="eyebrow">YOUR SKILL MAP</span><h2>Topic mastery</h2><p>Weighted from recent accuracy, difficult questions, retention, and consistency.</p><div className="mastery-detail-grid">{mastery.map(([name,score])=><article className="detail-card" key={name}><span className="eyebrow">TOPIC SIGNAL</span><strong>{score}%</strong><h3>{name}</h3><div className="progress-track"><span style={{width:`${score}%`}} /></div><dl><dt>Recent performance</dt><dd>{score-5}%</dd><dt>Next review</dt><dd>{score<60?'Tomorrow':'In 7 days'}</dd></dl></article>)}</div></section>}
function ProjectsView(){return <section className="simple-view"><span className="eyebrow">BUILD TO REMEMBER</span><h2>Project forge</h2><p>Turn concepts into proof of work.</p><div className="project-feature"><span className="eyebrow">IN PROGRESS · 34%</span><h2>E-commerce data platform</h2><p>Build a production-shaped pipeline from raw commerce events to a Power BI-ready gold layer.</p><div className="pipeline">CSV / API <b>-&gt;</b> BRONZE <b>-&gt;</b> SILVER <b>-&gt;</b> GOLD</div><div className="progress-track"><span style={{width:'34%'}} /></div></div></section>}
function AnalyticsView(){return <section className="simple-view"><span className="eyebrow">PERFORMANCE SIGNALS</span><h2>Your analytics</h2><p>Small trends compound into durable skill.</p><div className="analytics-grid"><div className="chart-card"><span>Accuracy over time</span><strong>76% <small>+8%</small></strong><div className="fake-chart" /></div><div className="stats-card"><span className="eyebrow">THIS WEEK</span>{[['Questions answered','87'],['Study time','8h 35m'],['XP earned','+420'],['Avg. difficulty','3.4 / 5']].map(([label,value])=><div className="stat-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section>}
