export type InterviewTopic = 'SQL' | 'Python' | 'Pandas' | 'PySpark' | 'Databricks' | 'Data Engineering' | 'Data Warehousing' | 'Airflow' | 'Cloud' | 'Power BI' | 'Analytics' | 'Statistics' | 'System Design' | 'Behavioral';
export type InterviewQuestion = { id: string; topic: InterviewTopic; prompt: string; kind: 'Coding' | 'Scenario' | 'Conceptual' | 'Behavioral'; difficulty: 'Easy' | 'Medium' | 'Hard'; sourceCount: number; confidence: 'HIGH' | 'MEDIUM' | 'LOW'; sourceName: string; sourceUrl: string; firstSeen: string; lastVerified: string };

export const sourceRegistry = [
  { name: 'Public GitHub interview repositories', category: 'Public repository', url: 'https://github.com/search?q=data+engineering+interview&type=repositories', status: 'Configured source' },
  { name: 'Apache Spark documentation', category: 'Official engineering source', url: 'https://spark.apache.org/docs/latest/', status: 'Configured source' },
  { name: 'PostgreSQL documentation', category: 'Official engineering source', url: 'https://www.postgresql.org/docs/', status: 'Configured source' },
  { name: 'AWS data engineering guidance', category: 'Official engineering source', url: 'https://aws.amazon.com/what-is/data-engineering/', status: 'Configured source' },
];

export const interviewQuestions: InterviewQuestion[] = [
  { id: 'sql-top-revenue', topic: 'SQL', prompt: 'Write SQL to find the top three customers by revenue in each region over the last 90 days. Handle ties explicitly.', kind: 'Coding', difficulty: 'Medium', sourceCount: 8, confidence: 'HIGH', sourceName: 'Public interview pattern registry', sourceUrl: 'https://www.postgresql.org/docs/current/tutorial-window.html', firstSeen: '2026-07-14', lastVerified: '2026-09-18' },
  { id: 'sql-duplicates', topic: 'SQL', prompt: 'Find duplicate customer records while preserving the latest record when timestamps tie.', kind: 'Coding', difficulty: 'Medium', sourceCount: 6, confidence: 'HIGH', sourceName: 'Public interview pattern registry', sourceUrl: 'https://www.postgresql.org/docs/current/functions-window.html', firstSeen: '2026-06-21', lastVerified: '2026-09-18' },
  { id: 'python-etl', topic: 'Python', prompt: 'Design a Python transformation that normalizes nested JSON events and reports malformed records without stopping the batch.', kind: 'Coding', difficulty: 'Medium', sourceCount: 5, confidence: 'MEDIUM', sourceName: 'Public interview pattern registry', sourceUrl: 'https://docs.python.org/3/library/json.html', firstSeen: '2026-07-02', lastVerified: '2026-09-16' },
  { id: 'pandas-cleaning', topic: 'Pandas', prompt: 'Given duplicate orders with missing customer IDs, explain and implement a safe cleaning sequence that preserves auditability.', kind: 'Coding', difficulty: 'Medium', sourceCount: 4, confidence: 'MEDIUM', sourceName: 'Public interview pattern registry', sourceUrl: 'https://pandas.pydata.org/docs/user_guide/merging.html', firstSeen: '2026-05-09', lastVerified: '2026-09-15' },
  { id: 'spark-join', topic: 'PySpark', prompt: 'A 500 million row events table joins to a 10 million row customer table. Explain when a broadcast join helps and what you monitor.', kind: 'Scenario', difficulty: 'Hard', sourceCount: 7, confidence: 'HIGH', sourceName: 'Spark public documentation pattern', sourceUrl: 'https://spark.apache.org/docs/latest/sql-performance-tuning.html', firstSeen: '2026-06-04', lastVerified: '2026-09-18' },
  { id: 'delta-merge', topic: 'Databricks', prompt: 'Explain how you would use an idempotent Delta MERGE for an incremental pipeline that can be retried.', kind: 'Scenario', difficulty: 'Medium', sourceCount: 5, confidence: 'HIGH', sourceName: 'Databricks public documentation pattern', sourceUrl: 'https://docs.databricks.com/aws/en/delta/merge', firstSeen: '2026-07-19', lastVerified: '2026-09-17' },
  { id: 'scd2', topic: 'Data Warehousing', prompt: 'Explain SCD Type 2, its effective-date columns, and how facts resolve the correct dimension version.', kind: 'Conceptual', difficulty: 'Medium', sourceCount: 5, confidence: 'HIGH', sourceName: 'Public interview pattern registry', sourceUrl: 'https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/', firstSeen: '2026-04-18', lastVerified: '2026-09-14' },
  { id: 'airflow-backfill', topic: 'Airflow', prompt: 'A daily DAG failed for three days. Describe a safe backfill plan that avoids duplicate downstream data.', kind: 'Scenario', difficulty: 'Hard', sourceCount: 4, confidence: 'MEDIUM', sourceName: 'Airflow public documentation pattern', sourceUrl: 'https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/backfill.html', firstSeen: '2026-06-29', lastVerified: '2026-09-12' },
  { id: 'system-design', topic: 'System Design', prompt: 'Design a pipeline processing 100 million events per day with replay, data quality checks, lineage, and cost-aware storage.', kind: 'Scenario', difficulty: 'Hard', sourceCount: 9, confidence: 'HIGH', sourceName: 'Public engineering design pattern registry', sourceUrl: 'https://aws.amazon.com/architecture/', firstSeen: '2026-05-27', lastVerified: '2026-09-18' },
  { id: 'powerbi-kpi', topic: 'Power BI', prompt: 'A business user says a KPI changed after filtering by region. How would you debug the DAX filter context and explain the result?', kind: 'Scenario', difficulty: 'Medium', sourceCount: 3, confidence: 'LOW', sourceName: 'Public interview pattern registry', sourceUrl: 'https://learn.microsoft.com/power-bi/transform-model/desktop-quickstart-learn-dax-basics', firstSeen: '2026-08-01', lastVerified: '2026-09-10' },
];

export const trendSignals = [
  ['SQL', 91], ['PySpark', 78], ['Python', 68], ['Data Warehousing', 61], ['Databricks', 57], ['Airflow', 39], ['Cloud', 44],
] as const;
