export type MasteryQuestion = { prompt: string; explanation: string; example: string };
export type MasteryTopic = { name: string; subtopics: string[]; questions: MasteryQuestion[] };

const q = (prompt: string, explanation: string, example: string): MasteryQuestion => ({ prompt, explanation, example });

export const masteryCurriculum: MasteryTopic[] = [
  { name: 'SQL', subtopics: ['Joins', 'CTEs', 'Window functions', 'Query optimization'], questions: [
    q('Find the top three products by revenue.', 'Aggregate revenue, rank within the result, then keep ranks 1 to 3.', 'SUM(amount) with DENSE_RANK() OVER (ORDER BY revenue DESC).'),
    q('Find duplicate customer records while keeping the latest.', 'Partition by the business key and order by the newest timestamp.', 'ROW_NUMBER() OVER (PARTITION BY email ORDER BY updated_at DESC).'),
    q('Explain ROW_NUMBER versus DENSE_RANK.', 'ROW_NUMBER is unique; DENSE_RANK keeps equal values at the same rank without gaps.', 'Scores 100, 100, 90 become row numbers 1,2,3 but dense ranks 1,1,2.'),
    q('Calculate a seven-day rolling revenue total.', 'Use a window frame ordered by date so each row sees its recent history.', 'SUM(revenue) OVER (ORDER BY order_date ROWS 6 PRECEDING).'),
    q('Return customers with no orders.', 'Use an anti-join pattern and preserve the customer side.', 'LEFT JOIN orders ... WHERE orders.customer_id IS NULL.'),
    q('When should a CTE be used?', 'Use a CTE to name a logical step and make a multi-stage query readable.', 'WITH daily AS (...) SELECT ... FROM daily.'),
    q('How do NULLs affect COUNT?', 'COUNT(*) counts rows, while COUNT(column) ignores NULL values.', 'COUNT(*) = 10 and COUNT(email) = 8 means two emails are NULL.'),
    q('How would you diagnose a slow query?', 'Inspect the execution plan, cardinality, joins, filters, and indexes.', 'EXPLAIN (ANALYZE, BUFFERS) SELECT ...;'),
    q('Find the second-highest salary per department.', 'Rank inside each department and filter the desired rank.', 'DENSE_RANK() OVER (PARTITION BY department_id ORDER BY salary DESC).'),
    q('Make an incremental query rerunnable.', 'Use a stable watermark and an idempotent merge key rather than blind append.', 'WHERE updated_at >= :last_watermark followed by MERGE on order_id.'),
  ]},
  { name: 'Python', subtopics: ['Data structures', 'Functions', 'Exceptions', 'JSON and APIs'], questions: [
    q('Count event types in a list of dictionaries.', 'A dictionary accumulator gives O(n) time and handles new event types.', 'counts[event["type"]] = counts.get(event["type"], 0) + 1.'),
    q('Write a generator for a large file.', 'Yield one parsed record at a time so memory stays bounded.', 'def rows(path):\n  for line in open(path): yield json.loads(line)'),
    q('Flatten nested JSON safely.', 'Read optional keys with defaults and validate types before transformation.', 'event.get("user", {}).get("id") or "unknown".'),
    q('Design a retryable API request.', 'Retry transient failures with bounded exponential backoff, not every error.', 'delay = min(2 ** attempt, 30) before the next request.'),
    q('When should a function raise an exception?', 'Raise when the caller cannot safely continue with the returned value.', 'raise ValueError("amount must be positive")'),
    q('Remove duplicates while preserving order.', 'A seen set tracks membership while the output list preserves first occurrence.', 'if item not in seen: seen.add(item); result.append(item).'),
    q('Explain list versus tuple.', 'Lists are mutable; tuples express fixed records and can be hashable.', 'coordinates = (lat, lon); batch = [row1, row2].'),
    q('Create a context manager for a resource.', 'Context managers guarantee cleanup even when a block raises.', 'with open(path) as file: process(file).'),
    q('Validate a configuration before a job runs.', 'Fail early with clear messages instead of discovering missing settings mid-pipeline.', 'required = ["BUCKET", "REGION"]; missing = [x for x in required if not os.getenv(x)].'),
    q('Explain shallow versus deep copy.', 'A shallow copy shares nested objects; a deep copy recursively duplicates them.', 'copy.deepcopy(config) prevents nested mutation leaks.'),
  ]},
  { name: 'Pandas', subtopics: ['Cleaning', 'Merge and join', 'Groupby', 'Time series'], questions: [
    q('Handle missing customer IDs without losing auditability.', 'Separate invalid rows, record the reason, and only clean valid rows.', 'bad = df[df.customer_id.isna()].assign(error="missing_customer_id").'),
    q('Join orders to customers.', 'Use merge with explicit validation to catch unexpected cardinality.', 'orders.merge(customers, on="customer_id", how="left", validate="many_to_one").'),
    q('Detect duplicate records.', 'Use duplicated on the natural key and keep all copies for review.', 'df[df.duplicated(["customer_id", "order_date"], keep=False)].'),
    q('Aggregate sales by region.', 'Groupby followed by named aggregations produces a clean summary.', 'df.groupby("region", as_index=False).agg(revenue=("amount", "sum")).'),
    q('Parse timestamps consistently.', 'Convert at ingestion with an explicit timezone policy.', 'pd.to_datetime(df["created_at"], utc=True, errors="coerce").'),
    q('Fill missing numeric values.', 'Choose a business-aware strategy and preserve an imputation flag.', 'df["amount_missing"] = df.amount.isna(); df.amount.fillna(0).'),
    q('Compare two DataFrames.', 'Use merge with indicator to find additions and removals.', 'a.merge(b, how="outer", indicator=True).'),
    q('Avoid chained assignment.', 'Use .loc or assign so Pandas knows which frame should change.', 'df.loc[df.active, "score"] = 1.'),
    q('Create a monthly time series.', 'Set a datetime index and resample with a defined aggregation.', 'df.set_index("date").amount.resample("MS").sum().'),
    q('Explain apply performance trade-offs.', 'Vectorized operations are usually faster and clearer than row-wise apply.', 'df["total"] = df.price * df.quantity instead of apply(axis=1).'),
  ]},
  { name: 'Analytics', subtopics: ['KPIs', 'EDA', 'Correlation', 'Experiment design'], questions: [
    q('Diagnose a sudden metric drop.', 'Check definition, data freshness, segments, denominator, and upstream changes.', 'Compare yesterday by region and verify row counts first.'),
    q('Choose a north-star metric.', 'Tie it to durable user or business value, not a shallow activity count.', 'Repeat purchase rate is stronger than raw page views for commerce.'),
    q('Explain correlation versus causation.', 'Correlation measures association; experiments or strong design are needed for causation.', 'Ad spend and sales can correlate because seasonality drives both.'),
    q('Calculate conversion rate correctly.', 'Use a consistent eligible denominator and define the time window.', 'completed_checkouts / started_checkouts for the same cohort.'),
    q('Design an A/B test.', 'Specify hypothesis, randomization unit, primary metric, power, and guardrails.', 'Test checkout copy with conversion as primary and refunds as guardrail.'),
    q('Handle an outlier.', 'Investigate whether it is an error, rare valid event, or a process change.', 'Keep a valid enterprise order but cap only for a clearly stated model.'),
    q('Explain a confidence interval.', 'It expresses uncertainty around an estimated effect under the sampling procedure.', 'A 95% interval gives a range, not a 95% chance the fixed effect moves.'),
    q('Build a retention cohort.', 'Group users by first activity period and measure return behavior over age.', 'Month-0 users = 100%; Month-1 retained / Month-0 users.'),
    q('Choose a chart for a trend.', 'A line chart shows change over ordered time; avoid pie charts for long series.', 'Daily active users over 12 weeks uses a line chart.'),
    q('Explain Simpson’s paradox.', 'An aggregate trend can reverse after splitting by a confounding group.', 'Overall conversion rises while conversion falls in every traffic channel.'),
  ]},
  { name: 'Data Warehousing', subtopics: ['Star schema', 'SCD Type 1', 'SCD Type 2', 'Fact and dimension design'], questions: [
    q('Design a sales star schema.', 'Put measurable events in a fact and descriptive entities in dimensions.', 'fact_sales joins dim_customer, dim_product, and dim_date.'),
    q('Implement SCD Type 1.', 'Overwrite the dimension value when history is not required.', 'UPDATE dim_customer SET city = new_city WHERE customer_key = ...'),
    q('Implement SCD Type 2.', 'Expire the old row and insert a new version with effective dates.', 'is_current=false, valid_to=load_time; then insert is_current=true.'),
    q('Choose a fact table grain.', 'Declare exactly what one row represents before adding measures.', 'One row per order line, not one row per order and line mixed.'),
    q('Explain surrogate keys.', 'A warehouse key decouples history from unstable source identifiers.', 'customer_key=42 can represent one historical version of source id C7.'),
    q('Handle late-arriving facts.', 'Load an inferred dimension member or quarantine the fact until context arrives.', 'Insert an unknown customer member, then repair the foreign key later.'),
    q('Model a date dimension.', 'Precompute calendar attributes so reporting logic stays consistent.', 'date_key=20260919, fiscal_week=38, is_weekend=false.'),
    q('Explain conformed dimensions.', 'A shared dimension lets facts from different processes be compared consistently.', 'dim_date is reused by sales and support facts.'),
    q('Prevent duplicate fact loads.', 'Use a natural event key, load audit, and idempotent merge.', 'MERGE on source_system + event_id.'),
    q('Partition a warehouse table.', 'Partition by a common filter such as event date while avoiding tiny partitions.', 'PARTITION BY RANGE (event_date) monthly.'),
  ]},
  { name: 'PySpark', subtopics: ['DataFrames', 'Joins', 'Windows', 'Partitions and shuffle'], questions: [
    q('Optimize a broadcast join.', 'Broadcast only a dimension that fits executor memory to avoid a large-side shuffle.', 'events.join(broadcast(customers), "customer_id").'),
    q('Deduplicate with a window.', 'Rank records per key and keep the deterministic first row.', 'row_number over partitionBy(key).orderBy(desc(updated_at)).'),
    q('Diagnose a slow Spark job.', 'Inspect stages, shuffle read, spill, skew, input size, and executor health.', 'Spark UI shows one task taking 10x longer than peers.'),
    q('Explain repartition versus coalesce.', 'Repartition reshuffles to increase or rebalance partitions; coalesce reduces with less shuffle.', 'df.repartition(200, "date") versus df.coalesce(20).'),
    q('Avoid collecting large data.', 'Keep computation distributed and collect only small aggregates or samples.', 'df.groupBy("status").count().collect() is safer than df.collect().'),
    q('Use Spark SQL for a window.', 'Register a DataFrame and express ranking with SQL when it improves readability.', 'spark.sql("SELECT *, ROW_NUMBER() OVER (...) AS rn FROM events").'),
    q('Handle data skew.', 'Salt hot keys, broadcast a small side, or split heavy keys and recombine.', 'salt = floor(rand()*10) for a known hot customer.'),
    q('Explain cache use.', 'Cache only reused, expensive results and materialize intentionally.', 'df.cache(); df.count(); then reuse df.'),
    q('Write a safe aggregation.', 'Select needed columns, filter early, and aggregate at the required grain.', 'events.filter(col("date") >= cutoff).groupBy("region").sum("amount").'),
    q('Optimize small files.', 'Control output partitions and compact files so downstream reads are efficient.', 'coalesce before write, then periodic compaction.'),
  ]},
  { name: 'Databricks', subtopics: ['Delta Lake', 'Medallion architecture', 'Jobs', 'Optimization'], questions: [
    q('Build a bronze-to-silver flow.', 'Bronze preserves raw input; silver validates, cleans, and standardizes it.', 'Auto Loader writes bronze, then a silver table enforces types.'),
    q('Write an idempotent Delta MERGE.', 'Match on a stable business key and update or insert deterministically.', 'MERGE INTO gold USING updates ON gold.id=updates.id.'),
    q('Explain OPTIMIZE and VACUUM.', 'OPTIMIZE compacts files; VACUUM removes old files after retention safeguards.', 'OPTIMIZE gold ZORDER BY (customer_id); VACUUM gold.'),
    q('Use Delta history for debugging.', 'Table history shows operations and versions for audit and rollback analysis.', 'DESCRIBE HISTORY gold LIMIT 10.'),
    q('Design a medallion architecture.', 'Separate raw, cleaned, and serving concerns to make quality and lineage visible.', 'bronze events -> silver typed events -> gold daily metrics.'),
    q('Schedule a Databricks job.', 'Define tasks, dependencies, parameters, retries, and an owner.', 'job parameters include processing_date and target_catalog.'),
    q('Handle schema evolution.', 'Allow only controlled changes and alert on breaking or unexpected columns.', 'mergeSchema for approved additive columns, not blind acceptance.'),
    q('Explain time travel.', 'Delta versions let you inspect or restore prior table states within retention.', 'SELECT * FROM table VERSION AS OF 42.'),
    q('Monitor a production notebook.', 'Capture duration, rows, failures, data quality, and cluster metrics.', 'send task metrics to an alert when row count drops 40%.'),
    q('Separate environments.', 'Use catalogs, schemas, permissions, and CI promotion between dev and prod.', 'dev_catalog.silver becomes prod_catalog.silver after validation.'),
  ]},
  { name: 'Cloud', subtopics: ['S3', 'IAM', 'Glue', 'Monitoring'], questions: [
    q('Design an S3 data lake.', 'Use predictable prefixes, immutable raw data, lifecycle rules, and encryption.', 's3://lake/bronze/orders/ingest_date=2026-09-19/.'),
    q('Choose least-privilege access.', 'Grant only required actions on required resources and review them regularly.', 'Allow GetObject on one prefix instead of s3:* on the bucket.'),
    q('Monitor a failed pipeline.', 'Combine workflow logs, metrics, alarms, and correlation IDs to find the fault.', 'CloudWatch alarm on failed Glue runs pages the owner.'),
    q('Explain S3 consistency and retries.', 'Make writes idempotent and use retries for transient network failures.', 'write to a deterministic key and safely retry the upload.'),
    q('Choose a Glue crawler carefully.', 'Crawlers infer schemas but need boundaries and review to avoid drift.', 'scope crawler to bronze/orders and compare schema changes.'),
    q('Protect sensitive data.', 'Encrypt at rest and transit, minimize access, and mask or tokenize sensitive fields.', 'KMS key plus column masking for customer email.'),
    q('Design a cloud cost guardrail.', 'Track storage, compute, requests, and idle resources with budgets and alerts.', 'tag jobs by team and alert when monthly spend crosses threshold.'),
    q('Handle cross-account data access.', 'Use explicit roles, bucket policies, trust relationships, and audit logs.', 'producer bucket trusts a consumer role for one prefix.'),
    q('Build resilient batch storage.', 'Use versioned immutable landing files and manifests for complete batches.', 'manifest.json lists all files for batch_20260919.'),
    q('Explain infrastructure as code.', 'Declare cloud resources repeatably so changes are reviewed and reproducible.', 'Terraform creates the bucket, role, policy, and alarm.'),
  ]},
  { name: 'Airflow', subtopics: ['DAGs', 'Scheduling', 'Retries', 'Backfill and sensors'], questions: [
    q('Make a DAG idempotent.', 'Tasks should write deterministic outputs or merge by a business key.', 'load_daily(date) replaces the partition rather than appending blindly.'),
    q('Plan a safe backfill.', 'Limit the date range, pause risky downstream actions, and validate each run.', 'backfill 2026-09-16 through 2026-09-18 after staging checks.'),
    q('Explain retry behavior.', 'Retries handle transient failures with delay and a bounded count.', 'retries=3, retry_delay=timedelta(minutes=10).'),
    q('Use a sensor responsibly.', 'Sensors wait on external state but should use a timeout and deferrable mode when possible.', 'wait for an object with timeout=3600.'),
    q('Set task dependencies.', 'The DAG graph should express data readiness and avoid hidden ordering assumptions.', 'extract >> validate >> transform >> publish.'),
    q('Choose a schedule.', 'Use a timezone-aware schedule that matches the data arrival contract.', 'schedule="0 6 * * *" with a documented UTC policy.'),
    q('Pass small metadata between tasks.', 'XCom is for small control values, not large datasets.', 'push run_id and object_key, not a DataFrame.'),
    q('Handle a failed downstream task.', 'Retry only safe tasks, alert the owner, and preserve logs and run context.', 'on_failure_callback sends the DAG and execution date.'),
    q('Prevent overlapping runs.', 'Use max_active_runs or a data interval lock when overlap is unsafe.', 'max_active_runs=1 for a non-idempotent legacy load.'),
    q('Test an Airflow DAG.', 'Parse it in CI and test task relationships, parameters, and key operators.', 'dag.test() verifies a local run with a fixed logical date.'),
  ]},
];
